name: movie_search_app
description: A simple movie search Flutter app.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # Compatible with Flutter 3.7.3 and Dart 2.19.2
  provider: ^6.0.0
  cupertino_icons: ^1.0.5


flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

  assets:
    - assets/fonts/
